require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CategoriasController do

  # This should return the minimal set of attributes required to create a valid
  # Categoria. As you add validations to Categoria, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoriasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all categorias as @categorias" do
      categoria = Categoria.create! valid_attributes
      get :index, {}, valid_session
      assigns(:categorias).should eq([categoria])
    end
  end

  describe "GET show" do
    it "assigns the requested categoria as @categoria" do
      categoria = Categoria.create! valid_attributes
      get :show, {:id => categoria.to_param}, valid_session
      assigns(:categoria).should eq(categoria)
    end
  end

  describe "GET new" do
    it "assigns a new categoria as @categoria" do
      get :new, {}, valid_session
      assigns(:categoria).should be_a_new(Categoria)
    end
  end

  describe "GET edit" do
    it "assigns the requested categoria as @categoria" do
      categoria = Categoria.create! valid_attributes
      get :edit, {:id => categoria.to_param}, valid_session
      assigns(:categoria).should eq(categoria)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Categoria" do
        expect {
          post :create, {:categoria => valid_attributes}, valid_session
        }.to change(Categoria, :count).by(1)
      end

      it "assigns a newly created categoria as @categoria" do
        post :create, {:categoria => valid_attributes}, valid_session
        assigns(:categoria).should be_a(Categoria)
        assigns(:categoria).should be_persisted
      end

      it "redirects to the created categoria" do
        post :create, {:categoria => valid_attributes}, valid_session
        response.should redirect_to(Categoria.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categoria as @categoria" do
        # Trigger the behavior that occurs when invalid params are submitted
        Categoria.any_instance.stub(:save).and_return(false)
        post :create, {:categoria => {}}, valid_session
        assigns(:categoria).should be_a_new(Categoria)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Categoria.any_instance.stub(:save).and_return(false)
        post :create, {:categoria => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested categoria" do
        categoria = Categoria.create! valid_attributes
        # Assuming there are no other categorias in the database, this
        # specifies that the Categoria created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Categoria.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => categoria.to_param, :categoria => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested categoria as @categoria" do
        categoria = Categoria.create! valid_attributes
        put :update, {:id => categoria.to_param, :categoria => valid_attributes}, valid_session
        assigns(:categoria).should eq(categoria)
      end

      it "redirects to the categoria" do
        categoria = Categoria.create! valid_attributes
        put :update, {:id => categoria.to_param, :categoria => valid_attributes}, valid_session
        response.should redirect_to(categoria)
      end
    end

    describe "with invalid params" do
      it "assigns the categoria as @categoria" do
        categoria = Categoria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Categoria.any_instance.stub(:save).and_return(false)
        put :update, {:id => categoria.to_param, :categoria => {}}, valid_session
        assigns(:categoria).should eq(categoria)
      end

      it "re-renders the 'edit' template" do
        categoria = Categoria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Categoria.any_instance.stub(:save).and_return(false)
        put :update, {:id => categoria.to_param, :categoria => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categoria" do
      categoria = Categoria.create! valid_attributes
      expect {
        delete :destroy, {:id => categoria.to_param}, valid_session
      }.to change(Categoria, :count).by(-1)
    end

    it "redirects to the categorias list" do
      categoria = Categoria.create! valid_attributes
      delete :destroy, {:id => categoria.to_param}, valid_session
      response.should redirect_to(categorias_url)
    end
  end

end
