require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TamanhosController do

  # This should return the minimal set of attributes required to create a valid
  # Tamanho. As you add validations to Tamanho, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TamanhosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tamanhos as @tamanhos" do
      tamanho = Tamanho.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tamanhos).should eq([tamanho])
    end
  end

  describe "GET show" do
    it "assigns the requested tamanho as @tamanho" do
      tamanho = Tamanho.create! valid_attributes
      get :show, {:id => tamanho.to_param}, valid_session
      assigns(:tamanho).should eq(tamanho)
    end
  end

  describe "GET new" do
    it "assigns a new tamanho as @tamanho" do
      get :new, {}, valid_session
      assigns(:tamanho).should be_a_new(Tamanho)
    end
  end

  describe "GET edit" do
    it "assigns the requested tamanho as @tamanho" do
      tamanho = Tamanho.create! valid_attributes
      get :edit, {:id => tamanho.to_param}, valid_session
      assigns(:tamanho).should eq(tamanho)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tamanho" do
        expect {
          post :create, {:tamanho => valid_attributes}, valid_session
        }.to change(Tamanho, :count).by(1)
      end

      it "assigns a newly created tamanho as @tamanho" do
        post :create, {:tamanho => valid_attributes}, valid_session
        assigns(:tamanho).should be_a(Tamanho)
        assigns(:tamanho).should be_persisted
      end

      it "redirects to the created tamanho" do
        post :create, {:tamanho => valid_attributes}, valid_session
        response.should redirect_to(Tamanho.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tamanho as @tamanho" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tamanho.any_instance.stub(:save).and_return(false)
        post :create, {:tamanho => {}}, valid_session
        assigns(:tamanho).should be_a_new(Tamanho)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tamanho.any_instance.stub(:save).and_return(false)
        post :create, {:tamanho => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tamanho" do
        tamanho = Tamanho.create! valid_attributes
        # Assuming there are no other tamanhos in the database, this
        # specifies that the Tamanho created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tamanho.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tamanho.to_param, :tamanho => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tamanho as @tamanho" do
        tamanho = Tamanho.create! valid_attributes
        put :update, {:id => tamanho.to_param, :tamanho => valid_attributes}, valid_session
        assigns(:tamanho).should eq(tamanho)
      end

      it "redirects to the tamanho" do
        tamanho = Tamanho.create! valid_attributes
        put :update, {:id => tamanho.to_param, :tamanho => valid_attributes}, valid_session
        response.should redirect_to(tamanho)
      end
    end

    describe "with invalid params" do
      it "assigns the tamanho as @tamanho" do
        tamanho = Tamanho.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tamanho.any_instance.stub(:save).and_return(false)
        put :update, {:id => tamanho.to_param, :tamanho => {}}, valid_session
        assigns(:tamanho).should eq(tamanho)
      end

      it "re-renders the 'edit' template" do
        tamanho = Tamanho.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tamanho.any_instance.stub(:save).and_return(false)
        put :update, {:id => tamanho.to_param, :tamanho => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tamanho" do
      tamanho = Tamanho.create! valid_attributes
      expect {
        delete :destroy, {:id => tamanho.to_param}, valid_session
      }.to change(Tamanho, :count).by(-1)
    end

    it "redirects to the tamanhos list" do
      tamanho = Tamanho.create! valid_attributes
      delete :destroy, {:id => tamanho.to_param}, valid_session
      response.should redirect_to(tamanhos_url)
    end
  end

end
